# Generated by Django 2.1.15 on 2021-12-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSymptoms', models.BooleanField()),
                ('hasCloseContact', models.BooleanField()),
                ('testResult', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pk', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('healthRecord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.HealthRecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name recorded', max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('nuid', models.CharField(default='no nuid recorded', max_length=20, null=True)),
                ('password', models.CharField(max_length=100)),
                ('healthRecord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.HealthRecord')),
            ],
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='questions',
            field=models.ManyToManyField(through='web_app.RecordedQuestion', to='web_app.Question'),
        ),
    ]
