# Generated by Django 2.1.15 on 2021-12-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='healthRecord',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.HealthRecord'),
        ),
    ]
