# Generated by Django 3.2.9 on 2021-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedquestion',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
