# Generated by Django 2.1.15 on 2021-12-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20211209_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Question'),
        ),
    ]
