# Generated by Django 3.2.9 on 2021-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_recordedquestion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedquestion',
            name='student_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
